### ISSUE TITLE
android 4.1.1(api 16) unfortunately FastLibrary has stopped 错误

### ISSUE THREAD

**Issue by tmxd09887** [AriesHoo/FastLibs#1]
android 4.1.1(api 16) 系统，打开主界面（SplashActivity），按android返回键，没有正常关闭app，而是出现unfortunately FastLibrary has stopped 错误

android monitor信息

`08-10 14:33:30.285 1818-1818/com.aries.library.fast.demo W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa622b288)
                                                                     
                                                                     --------- beginning of /dev/log/system
08-10 14:33:30.285 1818-1818/com.aries.library.fast.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           java.lang.SecurityException: Permission Denial: getTasks() from pid=1818, uid=10058 requires android.permission.GET_TASKS
                                                                               at android.os.Parcel.readException(Parcel.java:1425)
                                                                               at android.os.Parcel.readException(Parcel.java:1379)
                                                                               at android.app.ActivityManagerProxy.getTasks(ActivityManagerNative.java:2148)
                                                                               at android.app.ActivityManager.getRunningTasks(ActivityManager.java:667)
                                                                               at android.app.ActivityManager.getRunningTasks(ActivityManager.java:703)
                                                                               at com.aries.library.fast.util.AppUtil.isRunningForeground(AppUtil.java:96)
                                                                               at com.aries.library.fast.util.AppUtil.isRunningForeground(AppUtil.java:78)
                                                                               at com.aries.library.fast.util.ToastUtil.show(ToastUtil.java:61)
                                                                               at com.aries.library.fast.util.ToastUtil.show(ToastUtil.java:44)
                                                                               at com.aries.library.fast.util.ToastUtil.show(ToastUtil.java:37)
                                                                               at com.aries.library.fast.basis.BasisActivity.quitApp(BasisActivity.java:141)
                                                                               at com.aries.library.fast.module.activity.FastMainActivity.onBackPressed(FastMainActivity.java:95)
                                                                               at android.app.Activity.onKeyUp(Activity.java:2131)
                                                                               at android.view.KeyEvent.dispatch(KeyEvent.java:2633)
                                                                               at android.app.Activity.dispatchKeyEvent(Activity.java:2361)
                                                                               at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
                                                                               at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
                                                                               at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
                                                                               at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1819)
                                                                               at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3575)
                                                                               at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3545)
                                                                               at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:2795)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                               at android.os.Looper.loop(Looper.java:137)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                               at dalvik.system.NativeStart.main(Native Method)`

以上genymotion模拟，另外android 5.0.0没有这个错误

**Comment by AriesHoo** [comment]
1.0.1版本修复 因弹出toast之前判断应用是否前台低版本跑出异常造成
